### ISSUE TITLE
如何打印word、pdf之类的文档？

### ISSUE THREAD

**Issue by LoveqLRC** [GrassQing/CommonPrintProvider#9]

**Comment by GrassQing** [comment]
有的是指令打 看打印机。
有的是搞成图片 打图片

**Comment by LoveqLRC** [comment]
我看了源码，现在好像只有文字打印，和图片打印，如果要打印word和pdf之类的，那就难了，涉及对word，pdf的读取。

**Comment by GrassQing** [comment]
最近接触的一个项目 也是大衣的 发现 居然有 打印pdf的接口，具体里面是怎么做的没有进去看怎么，实现的，不过看参数是读流的形式进去 。抱歉，帮不上忙。
